# KSP State Police Synthetic Database - Expanded Multi-Ward & Multi-FIR Dataset Class

class CrimeDatabase:
    def __init__(self):
        self.firs = [
            {
                "fir_no": "FIR-2026-0041",
                "station": "Indiranagar PS",
                "ward": "Indiranagar",
                "district": "Bengaluru East",
                "date": "2026-06-12",
                "time": "21:30",
                "crime_type": "Armed Robbery",
                "ipc_sections": ["IPC 392", "IPC 397"],
                "victim": "Vikram Mehta",
                "accused": ["Ramesh 'Blade'"],
                "status": "Under Investigation",
                "lat": 12.9784,
                "lng": 77.6408,
                "financial_loss": 450000,
                "details": "Armed robbery at gunpoint near 100ft Road Indiranagar. Gold jewelry and cash seized."
            },
            {
                "fir_no": "FIR-2026-0089",
                "station": "Whitefield PS",
                "ward": "Whitefield",
                "district": "Bengaluru East",
                "date": "2026-06-14",
                "time": "14:15",
                "crime_type": "Cyber Phishing & Corporate Extortion",
                "ipc_sections": ["IT Act 66D", "IPC 420", "IPC 384"],
                "victim": "TechCorp Solutions India",
                "accused": ["Kiran 'Cyber'", "DarkByte Syndicate"],
                "status": "Charge Sheet Drafted",
                "lat": 12.9698,
                "lng": 77.7500,
                "financial_loss": 3200000,
                "details": "Ransomware extortion attack targeting IT server infrastructure. Rs 32 Lakhs transferred via Hawala accounts."
            },
            {
                "fir_no": "FIR-2026-0102",
                "station": "Koramangala PS",
                "ward": "Koramangala",
                "district": "Bengaluru South",
                "date": "2026-06-18",
                "time": "03:45",
                "crime_type": "Commercial Burglary",
                "ipc_sections": ["IPC 457", "IPC 380"],
                "victim": "Siddharth Electronics",
                "accused": ["Ramesh 'Blade'", "Shankar 'Pistol'"],
                "status": "Under Investigation",
                "lat": 12.9352,
                "lng": 77.6245,
                "financial_loss": 850000,
                "details": "Night burglary breaking shutter lock of electronics warehouse. Laptops and mobile phones stolen."
            },
            {
                "fir_no": "FIR-2026-0115",
                "station": "Jayanagar PS",
                "ward": "Jayanagar",
                "district": "Bengaluru South",
                "date": "2026-06-20",
                "time": "11:20",
                "crime_type": "Chain Snatching & Assault",
                "ipc_sections": ["IPC 379", "IPC 356"],
                "victim": "Sunitha Rao",
                "accused": ["Imran 'Strikers'"],
                "status": "Accused Arrested",
                "lat": 12.9250,
                "lng": 77.5938,
                "financial_loss": 180000,
                "details": "Two-wheeler gang snatched gold chain from pedestrian near Jayanagar 4th Block."
            },
            {
                "fir_no": "FIR-2026-0130",
                "station": "Rajajinagar PS",
                "ward": "Rajajinagar",
                "district": "Bengaluru West",
                "date": "2026-06-22",
                "time": "19:00",
                "crime_type": "Narcotics Trafficking",
                "ipc_sections": ["NDPS Act 21(C)", "NDPS Act 22"],
                "victim": "State of Karnataka",
                "accused": ["Eastside Syndicate", "Francis 'Narc'"],
                "status": "Under Investigation",
                "lat": 12.9982,
                "lng": 77.5530,
                "financial_loss": 1500000,
                "details": "Seizure of 4.5 kg MDMA contraband near Rajajinagar metro station."
            },
            {
                "fir_no": "FIR-2026-0142",
                "station": "HSR Layout PS",
                "ward": "HSR Layout",
                "district": "Bengaluru South",
                "date": "2026-06-24",
                "time": "16:30",
                "crime_type": "ATM Skimming & Fraud",
                "ipc_sections": ["IT Act 66C", "IPC 420"],
                "victim": "HDFC Bank Customers",
                "accused": ["Kiran 'Cyber'", "Vikram 'Skimmer'"],
                "status": "Under Investigation",
                "lat": 12.9121,
                "lng": 77.6445,
                "financial_loss": 940000,
                "details": "Deep-insert ATM skimmer devices installed at Sector 1 HSR Layout ATM kiosk."
            },
            {
                "fir_no": "FIR-2026-0155",
                "station": "Electronic City PS",
                "ward": "Electronic City",
                "district": "Bengaluru South",
                "date": "2026-06-25",
                "time": "22:10",
                "crime_type": "Vehicle Theft Ring",
                "ipc_sections": ["IPC 379", "IPC 411"],
                "victim": "Anand Kumar",
                "accused": ["Imran 'Strikers'", "Salim 'Chop'"],
                "status": "Under Investigation",
                "lat": 12.8452,
                "lng": 77.6602,
                "financial_loss": 620000,
                "details": "Lifting SUV vehicle using master key decoder near Phase 1 tech park."
            },
            {
                "fir_no": "FIR-2026-0168",
                "station": "Hebbal PS",
                "ward": "Hebbal",
                "district": "Bengaluru North",
                "date": "2026-06-28",
                "time": "02:15",
                "crime_type": "Highway Hijacking",
                "ipc_sections": ["IPC 395", "IPC 397"],
                "victim": "VRL Logistics Container",
                "accused": ["Shankar 'Pistol'", "Eastside Syndicate"],
                "status": "Under Investigation",
                "lat": 13.0358,
                "lng": 77.5970,
                "financial_loss": 2800000,
                "details": "Cargo container carrying electronic goods intercepted on Bellary Road."
            },
            {
                "fir_no": "FIR-2026-0180",
                "station": "Marathahalli PS",
                "ward": "Marathahalli",
                "district": "Bengaluru East",
                "date": "2026-07-01",
                "time": "15:45",
                "crime_type": "Investment Ponzi Scam",
                "ipc_sections": ["IPC 420", "KPID Act 9"],
                "victim": "142 Retail Investors",
                "accused": ["DarkByte Syndicate", "Deepak 'Wealth'"],
                "status": "Under Investigation",
                "lat": 12.9569,
                "lng": 77.7011,
                "financial_loss": 6500000,
                "details": "Fake crypto trading portal promised 30% monthly ROI, defrauding 142 investors."
            },
            {
                "fir_no": "FIR-2026-0195",
                "station": "Malleshwaram PS",
                "ward": "Malleshwaram",
                "district": "Bengaluru West",
                "date": "2026-07-03",
                "time": "18:20",
                "crime_type": "Extortion & Threat",
                "ipc_sections": ["IPC 384", "IPC 506"],
                "victim": "Ganesh Jewelers",
                "accused": ["Eastside Syndicate"],
                "status": "Under Investigation",
                "lat": 13.0031,
                "lng": 77.5643,
                "financial_loss": 500000,
                "details": "Protection money extortion letters delivered with live ammunition."
            },
            {
                "fir_no": "FIR-2026-0210",
                "station": "Bellandur PS",
                "ward": "Bellandur",
                "district": "Bengaluru East",
                "date": "2026-07-05",
                "time": "12:00",
                "crime_type": "Real Estate Deed Forgery",
                "ipc_sections": ["IPC 468", "IPC 471"],
                "victim": "NRI Landowner Trust",
                "accused": ["Kiran 'Cyber'", "Ramesh 'Blade'"],
                "status": "Under Investigation",
                "lat": 12.9279,
                "lng": 77.6771,
                "financial_loss": 12000000,
                "details": "Forged land title documents used to secure Rs 1.2 Crore bank loan."
            },
            {
                "fir_no": "FIR-2026-0225",
                "station": "Yelahanka PS",
                "ward": "Yelahanka",
                "district": "Bengaluru North",
                "date": "2026-07-08",
                "time": "20:30",
                "crime_type": "Illegal Arms Seizure",
                "ipc_sections": ["Arms Act 25(1A)", "Arms Act 27"],
                "victim": "State of Karnataka",
                "accused": ["Shankar 'Pistol'"],
                "status": "Accused Arrested",
                "lat": 13.1007,
                "lng": 77.5963,
                "financial_loss": 350000,
                "details": "Seizure of 3 country-made pistols and 25 rounds of ammunition."
            }
        ]

        self.suspects = [
            {
                "id": "ACC-101",
                "name": "Ramesh 'Blade'",
                "alias": "Knife Ramesh",
                "age": 34,
                "gender": "Male",
                "risk_score": 92,
                "mo": "Armed robbery, shutter breaking, night burglary",
                "gang": "Eastside Syndicate",
                "recidivism_probability": "88%",
                "prior_convictions": 4,
                "status": "Active / Absconding",
                "ipc_history": ["IPC 392", "IPC 397", "IPC 457"]
            },
            {
                "id": "ACC-102",
                "name": "Kiran 'Cyber'",
                "alias": "DarkNet Kiran",
                "age": 28,
                "gender": "Male",
                "risk_score": 85,
                "mo": "Corporate ransomware, phishing, crypto hawala laundering",
                "gang": "DarkByte Syndicate",
                "recidivism_probability": "74%",
                "prior_convictions": 2,
                "status": "On Bail",
                "ipc_history": ["IT Act 66D", "IPC 420", "IPC 468"]
            },
            {
                "id": "ACC-103",
                "name": "Shankar 'Pistol'",
                "alias": "Desi Shankar",
                "age": 39,
                "gender": "Male",
                "risk_score": 95,
                "mo": "Contract killing, arms smuggling, highway robbery",
                "gang": "Eastside Syndicate",
                "recidivism_probability": "94%",
                "prior_convictions": 6,
                "status": "Under Custody",
                "ipc_history": ["IPC 302", "IPC 395", "Arms Act 25"]
            },
            {
                "id": "ACC-104",
                "name": "Imran 'Strikers'",
                "alias": "Chain Imran",
                "age": 26,
                "gender": "Male",
                "risk_score": 78,
                "mo": "Two-wheeler snatching, vehicle lifting",
                "gang": "Lone Operator",
                "recidivism_probability": "65%",
                "prior_convictions": 3,
                "status": "In Custody",
                "ipc_history": ["IPC 379", "IPC 356"]
            },
            {
                "id": "ACC-105",
                "name": "Francis 'Narc'",
                "alias": "Frankie",
                "age": 31,
                "gender": "Male",
                "risk_score": 89,
                "mo": "Synthetic drugs distribution, party narcotics",
                "gang": "Eastside Syndicate",
                "recidivism_probability": "82%",
                "prior_convictions": 3,
                "status": "Active",
                "ipc_history": ["NDPS Act 21", "NDPS Act 22"]
            },
            {
                "id": "ACC-106",
                "name": "Vikram 'Skimmer'",
                "alias": "Carder Vikky",
                "age": 29,
                "gender": "Male",
                "risk_score": 81,
                "mo": "ATM skimmer installation, cloned card withdrawals",
                "gang": "DarkByte Syndicate",
                "recidivism_probability": "70%",
                "prior_convictions": 2,
                "status": "Absconding",
                "ipc_history": ["IT Act 66C", "IPC 420"]
            },
            {
                "id": "ACC-107",
                "name": "Deepak 'Wealth'",
                "alias": "Ponzi Deepak",
                "age": 42,
                "gender": "Male",
                "risk_score": 87,
                "mo": "Investment fraud, multi-level Ponzi schemes",
                "gang": "Independent Ring",
                "recidivism_probability": "79%",
                "prior_convictions": 1,
                "status": "On Bail",
                "ipc_history": ["IPC 420", "KPID Act 9"]
            }
        ]

        self.networks = {
            "nodes": [
                {"id": "Ramesh Blade", "label": "Ramesh 'Blade' (Accused)", "group": "accused", "val": 25},
                {"id": "Kiran Cyber", "label": "Kiran 'Cyber' (Accused)", "group": "accused", "val": 22},
                {"id": "Shankar Pistol", "label": "Shankar 'Pistol' (Accused)", "group": "accused", "val": 28},
                {"id": "Francis Narc", "label": "Francis 'Narc' (Accused)", "group": "accused", "val": 20},
                {"id": "Vikram Skimmer", "label": "Vikram 'Skimmer' (Accused)", "group": "accused", "val": 18},
                {"id": "Eastside Syndicate", "label": "Eastside Syndicate (Gang)", "group": "gang", "val": 35},
                {"id": "DarkByte Syndicate", "label": "DarkByte Syndicate (Cyber Gang)", "group": "gang", "val": 30},
                {"id": "ACC-99482104", "label": "Shell Account ACC-9948", "group": "bank", "val": 18},
                {"id": "ACC-77381902", "label": "Crypto Wallet ACC-7738", "group": "bank", "val": 20},
                {"id": "ACC-11029481", "label": "Hawala Layer ACC-1102", "group": "bank", "val": 22},
                {"id": "FIR-2026-0041", "label": "Indiranagar Robbery", "group": "fir", "val": 15},
                {"id": "FIR-2026-0089", "label": "Whitefield Ransomware", "group": "fir", "val": 15},
                {"id": "FIR-2026-0130", "label": "Rajajinagar Narcotics", "group": "fir", "val": 15},
                {"id": "FIR-2026-0180", "label": "Marathahalli Ponzi Scam", "group": "fir", "val": 15}
            ],
            "edges": [
                {"from": "Ramesh Blade", "to": "Eastside Syndicate", "label": "Enforcer"},
                {"from": "Shankar Pistol", "to": "Eastside Syndicate", "label": "Commander"},
                {"from": "Francis Narc", "to": "Eastside Syndicate", "label": "Distributor"},
                {"from": "Kiran Cyber", "to": "DarkByte Syndicate", "label": "Lead Hacker"},
                {"from": "Vikram Skimmer", "to": "DarkByte Syndicate", "label": "Field Carder"},
                {"from": "Ramesh Blade", "to": "FIR-2026-0041", "label": "Suspect"},
                {"from": "Kiran Cyber", "to": "FIR-2026-0089", "label": "Primary Accused"},
                {"from": "Eastside Syndicate", "to": "ACC-99482104", "label": "Account Holder"},
                {"from": "DarkByte Syndicate", "to": "ACC-77381902", "label": "Crypto Cashout"},
                {"from": "ACC-99482104", "to": "ACC-11029481", "label": "Hawala Transfer ₹32L"},
                {"from": "Ramesh Blade", "to": "Shankar Pistol", "label": "Co-Accused"},
                {"from": "Francis Narc", "to": "FIR-2026-0130", "label": "Seized Contraband"},
                {"from": "Kiran Cyber", "to": "FIR-2026-0180", "label": "Portal Developer"}
            ]
        }

        self.socio_demographics = [
            {"ward": "Indiranagar", "poverty_rate": 8.2, "unemployment_rate": 6.1, "literacy_rate": 89.4, "bar_density": 18.5, "crime_rate_index": 68},
            {"ward": "Whitefield", "poverty_rate": 11.5, "unemployment_rate": 8.4, "literacy_rate": 91.2, "bar_density": 12.0, "crime_rate_index": 79},
            {"ward": "Koramangala", "poverty_rate": 7.5, "unemployment_rate": 5.9, "literacy_rate": 92.5, "bar_density": 22.4, "crime_rate_index": 72},
            {"ward": "Jayanagar", "poverty_rate": 6.1, "unemployment_rate": 4.8, "literacy_rate": 94.1, "bar_density": 8.2, "crime_rate_index": 42},
            {"ward": "Rajajinagar", "poverty_rate": 14.8, "unemployment_rate": 12.2, "literacy_rate": 86.5, "bar_density": 14.1, "crime_rate_index": 84},
            {"ward": "HSR Layout", "poverty_rate": 6.8, "unemployment_rate": 5.2, "literacy_rate": 93.0, "bar_density": 15.6, "crime_rate_index": 55},
            {"ward": "Electronic City", "poverty_rate": 13.2, "unemployment_rate": 10.5, "literacy_rate": 88.0, "bar_density": 10.4, "crime_rate_index": 64},
            {"ward": "Hebbal", "poverty_rate": 16.4, "unemployment_rate": 13.8, "literacy_rate": 84.2, "bar_density": 11.8, "crime_rate_index": 77},
            {"ward": "Marathahalli", "poverty_rate": 15.0, "unemployment_rate": 11.9, "literacy_rate": 87.1, "bar_density": 16.2, "crime_rate_index": 88},
            {"ward": "Malleshwaram", "poverty_rate": 5.4, "unemployment_rate": 4.2, "literacy_rate": 95.8, "bar_density": 7.5, "crime_rate_index": 38},
            {"ward": "Yelahanka", "poverty_rate": 12.8, "unemployment_rate": 9.7, "literacy_rate": 86.9, "bar_density": 9.1, "crime_rate_index": 59},
            {"ward": "Bellandur", "poverty_rate": 10.2, "unemployment_rate": 7.6, "literacy_rate": 90.5, "bar_density": 19.8, "crime_rate_index": 76}
        ]

        self.financial_transactions = [
            {"txn_id": "TXN-908124", "source_acc": "ACC-99482104", "target_acc": "ACC-11029481", "amount": 3200000, "timestamp": "2026-06-15 10:22", "flag": "Layering / Hawala Cycle"},
            {"txn_id": "TXN-908125", "source_acc": "ACC-11029481", "target_acc": "ACC-77381902", "amount": 2800000, "timestamp": "2026-06-15 11:04", "flag": "Crypto Off-Ramp"},
            {"txn_id": "TXN-908140", "source_acc": "ACC-44910283", "target_acc": "ACC-99482104", "amount": 1650000, "timestamp": "2026-06-19 16:45", "flag": "Burglary Proceeds Cashout"},
            {"txn_id": "TXN-908155", "source_acc": "ACC-88201948", "target_acc": "ACC-99482104", "amount": 1500000, "timestamp": "2026-06-23 09:12", "flag": "Narcotics Hawala Sourcing"},
            {"txn_id": "TXN-908170", "source_acc": "ACC-77381902", "target_acc": "ACC-55102938", "amount": 4200000, "timestamp": "2026-07-02 14:10", "flag": "Ponzi Investment Cashout"},
            {"txn_id": "TXN-908185", "source_acc": "ACC-11029481", "target_acc": "ACC-33910284", "amount": 12000000, "timestamp": "2026-07-06 17:30", "flag": "Land Forgery Loan Transfer"},
            {"txn_id": "TXN-908200", "source_acc": "ACC-99482104", "target_acc": "ACC-66019283", "amount": 3200000, "timestamp": "2026-07-09 11:15", "flag": "Extortion Cash Layering"}
        ]

        self.audit_logs = [
            {"time": "2026-07-26 14:10:02", "user": "IO_Ramesh_Inspector", "role": "Investigator", "action": "Executed natural language RAG query: 'FIRs in Indiranagar'"},
            {"time": "2026-07-26 14:15:22", "user": "Analyst_Priya", "role": "Analyst", "action": "Rendered Vis.js Criminal Graph with 14 nodes and 13 edges"},
            {"time": "2026-07-26 14:22:45", "user": "SP_Kumar", "role": "Supervisor", "action": "Generated XAI evidence trail for Accused Ramesh 'Blade'"},
            {"time": "2026-07-26 14:30:10", "user": "DGP_Office", "role": "Policymaker", "action": "Triggered ML Recidivism Model Training Pipeline"}
        ]

# Global instance compatibility
CRIME_DATABASE = {
    "firs": CrimeDatabase().firs,
    "suspects": CrimeDatabase().suspects,
    "networks": CrimeDatabase().networks,
    "socio_demographics": CrimeDatabase().socio_demographics,
    "financial_transactions": CrimeDatabase().financial_transactions,
    "audit_logs": CrimeDatabase().audit_logs
}
